[package]
name = "wcspr"
version = "0.1.0"
authors = ["PICASWAP"]
edition = "2018"

[dependencies]
casper-contract = "1.3.3"
casper-types = "1.3.3"

[[bin]]
name = "token_staking_contract"
path = "src/token_staking.rs"
bench = false
doctest = false
test = false